# Generated by Django 3.1.7 on 2021-10-16 07:38

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '4. Box Sizes',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '2. Brands',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to=product.models.card_image)),
            ],
            options={
                'verbose_name_plural': '6. Cards',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': '1. Categories',
            },
        ),
        migrations.CreateModel(
            name='PremadeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.CharField(blank=True, default='lorem ipsum lorem ipsum lorem ipsum lorem ipsum', max_length=350, null=True)),
                ('feature1', models.CharField(blank=True, default='lorem ipsum lorem ipsum lorem ipsum lorem ipsum', max_length=250, null=True)),
                ('feature2', models.CharField(blank=True, default='lorem ipsum lorem ipsum lorem ipsum lorem ipsum', max_length=250, null=True)),
                ('feature3', models.CharField(blank=True, default='lorem ipsum lorem ipsum lorem ipsum lorem ipsum', max_length=250, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to=product.models.premadeproduct_image)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'verbose_name_plural': '9. Premade Products',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.CharField(blank=True, default='lorem ipsum lorem ipsum lorem ipsum lorem ipsum', max_length=350, null=True)),
                ('feature1', models.CharField(blank=True, default='lorem ipsum lorem ipsum lorem ipsum lorem ipsum', max_length=250, null=True)),
                ('feature2', models.CharField(blank=True, default='lorem ipsum lorem ipsum lorem ipsum lorem ipsum', max_length=250, null=True)),
                ('feature3', models.CharField(blank=True, default='lorem ipsum lorem ipsum lorem ipsum lorem ipsum', max_length=250, null=True)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to=product.models.product_image)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brandProducts', to='product.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryProducts', to='product.category')),
            ],
            options={
                'verbose_name_plural': '7. Products',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '3. Variants',
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=350, null=True)),
                ('itemNumber', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('image1', models.ImageField(upload_to=product.models.product_variation_image)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=product.models.product_variation_image)),
                ('price', models.PositiveIntegerField()),
                ('discountPrice', models.PositiveIntegerField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productVariations', to='product.product')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.variant')),
            ],
            options={
                'verbose_name_plural': '8. Product Variants',
            },
        ),
        migrations.CreateModel(
            name='PremadeProductVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=350, null=True)),
                ('itemNumber', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('image1', models.ImageField(upload_to=product.models.premade_productvariation_image)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=product.models.premade_productvariation_image)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('discountPrice', models.PositiveIntegerField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=10)),
                ('products', models.ManyToManyField(to='product.PremadeProduct')),
            ],
            options={
                'verbose_name_plural': '9. Premade Products Variation',
            },
        ),
        migrations.CreateModel(
            name='GiftBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, default='lorem ipsum lorem ipsum lorem ipsum lorem ipsum', max_length=350, null=True)),
                ('feature1', models.CharField(blank=True, default='lorem ipsum lorem ipsum lorem ipsum lorem ipsum', max_length=250, null=True)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to=product.models.gift_box_image)),
                ('boxsize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxSize', to='product.boxsize')),
            ],
            options={
                'verbose_name_plural': '5. Gift Box Types',
            },
        ),
    ]
