# Generated by Django 3.1.7 on 2021-10-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boxsize',
            options={'verbose_name_plural': '4. Box Sizes'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': '2. Brands'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name_plural': '6. Cards'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '1. Categories'},
        ),
        migrations.AlterModelOptions(
            name='giftbox',
            options={'verbose_name_plural': '5. Gift Box Types'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '7. Products'},
        ),
        migrations.AlterModelOptions(
            name='productvariation',
            options={'verbose_name_plural': '8. Product Variants'},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name_plural': '3. Variants'},
        ),
    ]
