# Generated by Django 3.1.7 on 2021-10-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
