# Generated by Django 3.1.7 on 2021-10-10 16:36

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211005_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.product_variation_image),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.product_variation_image),
        ),
        migrations.CreateModel(
            name='PremadeProductVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=350, null=True)),
                ('itemNumber', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=product.models.product_variation_image)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=product.models.product_variation_image)),
                ('price', models.PositiveIntegerField()),
                ('discountPrice', models.PositiveIntegerField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=10)),
                ('products', models.ManyToManyField(related_name='premadeProductVariations', to='product.Product')),
            ],
            options={
                'verbose_name_plural': '8. Premade Product Variation',
            },
        ),
        migrations.CreateModel(
            name='PremadeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.CharField(blank=True, default='lorem ipsum lorem ipsum lorem ipsum lorem ipsum', max_length=350, null=True)),
                ('feature1', models.CharField(blank=True, default='lorem ipsum lorem ipsum lorem ipsum lorem ipsum', max_length=250, null=True)),
                ('feature2', models.CharField(blank=True, default='lorem ipsum lorem ipsum lorem ipsum lorem ipsum', max_length=250, null=True)),
                ('feature3', models.CharField(blank=True, default='lorem ipsum lorem ipsum lorem ipsum lorem ipsum', max_length=250, null=True)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to=product.models.product_image)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premadeProducts', to='product.category')),
            ],
            options={
                'verbose_name_plural': '7. Products',
            },
        ),
    ]
