# Generated by Django 3.1.7 on 2021-10-10 16:49

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211010_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premadeproductvariation',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.premade_productvariation_image),
        ),
        migrations.AlterField(
            model_name='premadeproductvariation',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.premade_productvariation_image),
        ),
        migrations.DeleteModel(
            name='PremadeProduct',
        ),
    ]
