# Generated by Django 3.1.7 on 2021-10-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20211010_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premadeproductvariation',
            name='products',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
