# Generated by Django 3.1.7 on 2021-10-10 17:20

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20211010_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premadeproductvariation',
            options={'verbose_name_plural': '. Premade Product Variation'},
        ),
        migrations.CreateModel(
            name='PremadeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.CharField(blank=True, default='lorem ipsum lorem ipsum lorem ipsum lorem ipsum', max_length=350, null=True)),
                ('feature1', models.CharField(blank=True, default='lorem ipsum lorem ipsum lorem ipsum lorem ipsum', max_length=250, null=True)),
                ('feature2', models.CharField(blank=True, default='lorem ipsum lorem ipsum lorem ipsum lorem ipsum', max_length=250, null=True)),
                ('feature3', models.CharField(blank=True, default='lorem ipsum lorem ipsum lorem ipsum lorem ipsum', max_length=250, null=True)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to=product.models.premadeproduct_image)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'verbose_name_plural': '8. Premade Product',
            },
        ),
    ]
