# Generated by Django 3.1.7 on 2021-10-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20211010_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premadeproductvariation',
            options={'verbose_name_plural': '9. Premade Product Variation'},
        ),
        migrations.AlterField(
            model_name='premadeproductvariation',
            name='products',
            field=models.ManyToManyField(to='product.PremadeProduct'),
        ),
    ]
