# Generated by Django 3.2.7 on 2021-10-01 17:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gnm_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppUser',
            new_name='GnmUser',
        ),
    ]
