# Generated by Django 3.1.7 on 2021-10-03 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gnm_users', '0002_rename_appuser_gnmuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gnmuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gnmuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gnmusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
