# Generated by Django 3.1.7 on 2021-10-16 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardtype',
            name='card_message',
        ),
        migrations.RemoveField(
            model_name='giftboxitem',
            name='card_message',
        ),
        migrations.AddField(
            model_name='cardtype',
            name='card',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.card'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='card_content_back',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='card_content_front',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='recipient',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='sender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
