# Generated by Django 3.1.7 on 2021-10-04 17:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_boxitem_boxtype_cardtype_giftitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoxItem',
            new_name='GiftBoxItem',
        ),
    ]
