# Generated by Django 3.1.7 on 2021-10-05 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211005_2136'),
        ('order', '0003_auto_20211004_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boxtype',
            options={'verbose_name_plural': '1. Selected Box Type'},
        ),
        migrations.AlterModelOptions(
            name='cardtype',
            options={'verbose_name_plural': '2. Selected Card Type'},
        ),
        migrations.AlterModelOptions(
            name='giftboxitem',
            options={'verbose_name_plural': '4. Gift Box Items'},
        ),
        migrations.AlterModelOptions(
            name='giftitem',
            options={'verbose_name_plural': '3. Selected Gift Items'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': '7. Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': '6. Order Items'},
        ),
        migrations.AlterModelOptions(
            name='wishitem',
            options={'verbose_name_plural': '5. Wishlist Items'},
        ),
        migrations.CreateModel(
            name='CardMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.PositiveIntegerField(blank=True, null=True)),
                ('sender', models.PositiveIntegerField(blank=True, null=True)),
                ('card_content_front', models.CharField(blank=True, max_length=500, null=True)),
                ('card_content_back', models.CharField(blank=True, max_length=500, null=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='giftcard', to='product.card')),
            ],
            options={
                'verbose_name_plural': 'Card Messages',
            },
        ),
        migrations.AddField(
            model_name='giftboxitem',
            name='card_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.cardmessage'),
        ),
    ]
