# Generated by Django 3.1.7 on 2021-10-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20211016_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='giftboxitems',
        ),
        migrations.AddField(
            model_name='order',
            name='giftboxitems',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
