# Generated by Django 3.1.7 on 2021-10-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20211005_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmessage',
            name='card_content_back',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cardmessage',
            name='card_content_front',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cardmessage',
            name='recipient',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cardmessage',
            name='sender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
